### ISSUE TITLE
Inverted List Support

### ISSUE THREAD

**Issue by elliotfleming** [thomasrovayaz/react-native-draggable-dynamic-flatlist#4]
Thanks for your work improving this package! I was hoping you could help me out with an edge case...

I use inverted FlatList's in my app `transform: [{ scaleY: -1 }]` in order to simulate a chat style UI, where the beginning of the list is at the bottom of the page. When I begin dragging a row using the `DraggableFlatList`, however, it still behaves as if it was in the normal position (non-inverted), which caused it to jump to the top of the page and move in the opposite direction intended.

Is there an easy way to modify your source to support this? I tried playing around with it for a while to no avail. Thanks for your help!

**Comment by thomasrovayaz** [comment]
Hello,
I think it's too late for an answer but maybe someone will pass through here...
There is 2 part to update, first the initialization in
`move = (hoverComponent, index)`
In this function I initialize position (in the array and on the screen), so it has to be updated to fit the new config
And then in the rest of the code, you have to invert this._previousIndex and this._nextIndex, especially in `getSpacerIndex = (move)`

**Comment by wishgoods** [comment]
hi guys, I'm just looking for any attention here seems like maybe this package is not maintained but it's the best I found for my needs.
I'm experiencing something wierd in my app. 
I tried from scratch using this package on a list but when I try to drag I get an error in the measure function saying that the ref object is null . 
did any of you get passed this error?  
 

btw... I'm using expo and it's a web build. you are my last hope of this.

Uncaught TypeError: Cannot read properties of null (reading 'measure')
    at onLayout (index.js:370:1)
    at index.js:48:1
    at index.js:49:1


Thanks in advanced for any help you may offer

**Comment by wishgoods** [comment]
btw - this is how I render 

<DraggableFlatList
                // onLayout={() => {}}
                
                scrollPercent={5}
                onMoveEnd={({ data }) => {
                  dragToggle && setListItems(data);
                }}
                data={listItems?.filter((element) => {
                  if (display_mode == 1) {
                    return !element.completed;
                  } else {
                    return element.completed;
                  }
                })}
                renderItem={renderItem}
                keyExtractor={(item, index) => "draggable-item-" + item.id}
              />
            )}
